/**
 * Example swagger.config.js for CLI usage
 */
module.exports = {
  // Path to your router file
  router: './src/routes/index.ts',
  
  // Export name (default: 'default' or 'router')
  routerExport: 'router',
  
  // Output file path
  output: './docs/swagger.yaml',
  
  // Output format: 'yaml' or 'json'
  format: 'yaml',
  
  // OpenAPI info section
  info: {
    title: 'My API',
    version: '1.0.0',
    description: 'API documentation generated by express-swagger-gen',
    contact: {
      name: 'API Support',
      email: 'support@example.com',
    },
    license: {
      name: 'MIT',
      url: 'https://opensource.org/licenses/MIT',
    },
  },
  
  // API servers
  servers: [
    { url: 'http://localhost:3000', description: 'Development' },
    { url: 'https://api.production.com', description: 'Production' },
  ],
  
  // Security schemes
  securitySchemes: {
    JWT: {
      type: 'http',
      scheme: 'bearer',
      bearerFormat: 'JWT',
      description: 'JWT Authentication',
    },
    ApiKey: {
      type: 'apiKey',
      in: 'header',
      name: 'X-API-Key',
      description: 'API Key Authentication',
    },
  },
  
  // Middleware names that indicate auth is required
  securityMiddlewares: ['verifyAuthorization', 'authenticate', 'auth', 'requireAuth'],
  
  // Map path segments to tag names
  tagMappings: {
    auth: 'Authentication',
    users: 'User Management',
    admin: 'Administration',
    health: 'Health Checks',
  },
  
  // Nested path mappings (for paths like /workspace/:id/feature)
  nestedTagMappings: {
    workspace: {
      users: 'Workspace Users',
      projects: 'Workspace Projects',
      settings: 'Workspace Settings',
      reports: 'Workspace Reports',
    },
  },
  
  // Extra endpoints not in router (webhooks, health checks, etc.)
  extraEndpoints: [
    { method: 'get', path: '/health' },
    { method: 'get', path: '/metrics' },
    { method: 'post', path: '/webhooks/stripe' },
  ],
  
  // Endpoints to exclude from documentation
  excludeEndpoints: [
    { method: 'get', path: '/internal/debug' },
  ],
};
